
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
    name: Heroku
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: b.dekker6@student.avans.nl
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: programmeren4-share-a-meal
